name: Generate 3D Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 每天自动生成一次

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@main
        with:
          user_name: jo1-yo
          output: ./profile-3d-contrib/profile-night-rainbow.svg
          theme: 0x00ffff
          transparent: true       #  背景透明
          hide_legend: true        #  去掉右侧圆环
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated 3D Contribution Graph"
          git push

