name: Generate 3D Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Graph
        run: |
          git clone https://github.com/yoshi389111/github-profile-3d-contrib.git
          cd github-profile-3d-contrib
          npm install
          node ./src/index.js --username jo1-yo --theme github-dark --no-bg --no-legend --no-radar
          cd ..
          mkdir -p profile-3d-contrib
          mv github-profile-3d-contrib/out/github-dark.svg ./profile-3d-contrib/profile-night-rainbow.svg

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated 3D Contribution Graph"
          git push
