name: Generate 3D Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Generate 3D Contribution Graph
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate 3D Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        with:
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: |
            {
              "type": "normal",
              "backgroundColor": "#00000000",
              "foregroundColor": "#ffffff",
              "strongColor": "#00ff00",
              "weakColor": "#004400",
              "radarColor": "#00000000",
              "growingAnimation": true,
              "contribColors": ["#004400", "#006600", "#008800", "#00aa00", "#00ff00"],
              "username": "jo1-yo"
            }
      
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Generated 3D Contribution Graph" && git push)
