name: Generate 3D Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 每天自动生成一次

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Graph
        uses: hako-mikan/github-profile-3d-contrib@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          user_name: jo1-yo
          output: ./profile-3d-contrib/profile-night-rainbow.svg
          theme: rainbow
          transparent: true     # ✅ 背景透明
          hide_legend: true      # ✅ 去掉圆环
          hide_radar: true       # ✅ 去掉雷达

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated 3D Contribution Graph"
          git push
